### PR TITLE
added name to DESCRIPTION

### PR DESCRIPTION
**Pull request by leehazel**
added name to DESCRIPTION

### CODE REVIEW

**Comment by leehazel** [comment]
I've looked for but cannot spot the error in the authors field.

**Comment by Doi90** [comment]
You have two different types of double quotation marks scattered
throughout. Copy-paste error, maybe?

**Comment by goldingn** [comment]
Ooh yeah, where'd you get those snazzy quotation marks from?

**Comment by goldingn** [comment]
(we can fix this on zoon hack day if you like)

**Comment by leehazel** [comment]
What y'all talking 'bout? I'll check tomorrow.

**Comment by Doi90** [comment]
You've got two different types (?) of double quotation marks in your code:

person(“Liz”, “Martin”, role = c("aut"), + email = “
emartin@student.unimelb.edu.au"))

The ones around 'Liz' and 'Martin' and at the beginning of your email (but
somehow not the end) are some sort of fancy quotation marks that look like
italics and a different font. Switching them all to the standard " " marks
(like around 'aut') should fix the error. I'm guessing it is from a
copy-paste error.

**Comment by leehazel** [comment]
Thanks, Dave. I'll check it out tomorrow. Weird, right?

**Comment by leehazel** [comment]
FIxed. Though mine are still italic, or similar, but not throwing an error any more.

**Comment by goldingn** [comment]
Now they're all curly! They need to be the straight vertical ones like in David's. 

It's amazing how many different characters there are for quotation marks. This has tripped me up so many times

**Comment by leehazel** [comment]
I can't make straight ones! I'll try again in a different text editor.

**Comment by leehazel** [comment]
It was reverting my straight ones to curly ones. Take three.

**Comment by goldingn** [comment]
Hurrah!

**Pull request merged**
