### PR TITLE
Temp

### PR DESCRIPTION
**Pull request by Doi90**
Made changes required to intro BPG (Liz argument, basic workflow, figure heights, list in putting it all together.

While GBIF/Bioclim were both working at the same time I ran devtools::build_vignetes()

### CODE REVIEW

**Comment by Doi90** [comment]
I have no idea what conflicts need to be resolved before this can merge? It doesn't show any merge conflicts when I look for them.

**Comment by goldingn** [comment]
Looks like your temp branch is way behind the Upstream master. You'll need to fetch the upstream, attempt to merge into temp, then fix the conflicts locally

**Comment by Doi90** [comment]
Weird, I did that this morning and it said I was up to date. I'll try again.

**Comment by goldingn** [comment]
maybe your master branch is up to date, but not this one?

**Pull request merged**
